version: "3"
services:
  mysql:
    image: mysql:5.7.10
    ports:
      - "53306:3306"
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TEST
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Asia/Shanghai
