version: "3.4"
services:
  mysql:
    image: dockerhub.datagrand.com/global/mysql:5.6
    ports:
      - "53306:3306"
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=data_grand
      - MYSQL_PASSWORD=23Knowledge
      - TZ=Asia/Shanghai
    command:
      --character-set-server=utf8 --collation-server=utf8_general_ci --ignore-db-dir=lost+found
